[package]
name = "fdb"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.2"
crc = "1.7"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "fdb"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"
